services:
  videograbber-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videograbber-bot-prod
    restart: always
    
    environment:
      # Production environment settings
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - DB_PATH=/app/data/bot.db
      - DATA_DIR=/app/data
      - TEMP_DIR=/app/data/temp
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    
    volumes:
      # Persistent data storage
      - bot_data_prod:/app/data
      - bot_logs_prod:/app/logs
    
    networks:
      - bot_network
    
    # Enhanced resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.2'
    
    # Enhanced health check for production
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app'); import bot.config; print('OK')"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  bot_data_prod:
    driver: local
  bot_logs_prod:
    driver: local

networks:
  bot_network:
    driver: bridge