services:
  videograbber-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videograbber-bot
    restart: unless-stopped
    
    environment:
      # Bot configuration - override these in .env file
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      
      # Database configuration
      - DB_PATH=/app/data/bot.db
      - DATA_DIR=/app/data
      - TEMP_DIR=/app/data/temp
      
      # Optional: Log level
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # Persistent data storage
      - bot_data:/app/data
      # Optional: Mount logs directory for easier access
      - bot_logs:/app/logs
    
    networks:
      - bot_network
    
    # Resource limits to prevent resource exhaustion
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app'); import bot.config; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  bot_data:
    driver: local
  bot_logs:
    driver: local

networks:
  bot_network:
    driver: bridge