services:
  - type: web
    name: videograbberbot
    runtime: python
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        value: 10000
      - key: WEBHOOK_HOST
        value: https://videograbberbot.onrender.com
      - key: YOUTUBE_COOKIES
        sync: false
      - key: YT_DLP_VERBOSE
        value: "NO"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1