services:
  - type: web
    name: videograbberbot
    runtime: python
    buildCommand: pip install -U pip && pip install -e .
    startCommand: python run.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1